# Site settings
title: WebConfs - A blog about web conferences
email: coolwebconfs@gmail.com
description: A blog about my favourite web conferences.
url: "http://webconfs.me" # the base hostname & protocol for your site
twitter_username: guilh

# Build settings
markdown: kramdown
permalink: /:title

# permalink: pretty
